import pyautogui as pg

# folder constants
GENERAL_MODEL_PATH = 'mdl/general.pickle'

# # eye action constants
EYE_AR_LOWER_THRESH = 0.17
# EYE_AR_EYEDN_THRESH = 0.19
# EYE_AR_UPPER_THRESH = 0.26
# EYE_AD_EYEUP_THRESH = 2.25
# EYE_AD_EYELR_THRESH = 2.25
EYE_MOVEMENT_THRESH = 3

# mouse action constants
MOUSE_DRAG_DISTANCE = 200
MOUSE_DRAG_DURATION = 0.3
MOUSE_SCROLL_DISTANCE = 10

# other constants
COUNT_DOWN_SECS = 5
NUM_IMAGES = 300
NUM_TN_IMAGES = 200
FRAME_RATE = 10
FILLED_GRAY_COLOR = 80

SCREEN_W, SCREEN_H = pg.size()
